### ISSUE TITLE
few improvements

### ISSUE THREAD

**Issue by renatko** [smi2/phpClickHouse#1]
Hi!
We use this library in own project, this works very well! But missing a few things, that it was production-ready.
I propose to make a few improvements:
- add composer.json
- `\ClickHouseDB\Settings` - there is a need to set any settings. Now in my fork I made `set()` as public. Maybe better way - pass settings via constructor in `Client`
- error handling as exceptions
- unit-tests

Please let me know, what you think about it and what is your roadmap?

**Comment by isublimity** [comment]
Hi, thx for feedback)

I add settings method: https://github.com/smi2/phpClickHouse#settings

The main direction is to add new features, like "drop partitions in cluster" and "array in column".
In the background : unit-test, composer and normal exception.

roadmap : https://github.com/smi2/phpClickHouse#todos

**Comment by isublimity** [comment]
add exceptions https://github.com/smi2/phpClickHouse/blob/master/example/exam11_errors.php

**Comment by isublimity** [comment]
add composer )

**Comment by isublimity** [comment]
add phpunit
