### ISSUE TITLE
Not have response

### ISSUE THREAD

**Issue by simPod** [smi2/phpClickHouse#105]
(In new version `No response returned` since https://github.com/smi2/phpClickHouse/pull/100)

"Not have response" exception is thrown for some reason when running some async code.

Discovered that this change is responsible for the broke async functionality

![image](https://user-images.githubusercontent.com/327717/47257616-75b55f80-d490-11e8-8fb4-5635274781d8.png)

Currently I'm investigating what that code does and why is it required. IMO the cause is hidden in those magic numbers there that somehow breaks out of the loop.

------------------------

BTW would be great if we could use commits properly, that is to have one commit to contain working addition to the code. This change is splat across 4 commits and changes are not easy to track. Eg. there's SelectAsyncTest added in https://github.com/smi2/phpClickHouse/commit/96a5a46d6cf3f3953f1f3570c87ff8c9cb2cab1d#diff-9256582a3f34d36cf3e4a034c48f49d3R1 and after trying to find it I discover that it was deleted 4 commits later https://github.com/smi2/phpClickHouse/commit/b6f4b71ab1c94f1c21d1fd9b5ed91e6c2654d077 :(

**Comment by simPod** [comment]
I started to rewrite the whole HTTP layer that will also fix it

**Comment by isublimity** [comment]
async functionality - full work

**Comment by simPod** [comment]
Was broken in metioned commits...
