### ISSUE TITLE
Correct query format parsing

### ISSUE THREAD

**Issue by vvhungy** [smi2/phpClickHouse#108]
Test case: 
`$a = $client->select("select * from table_name FORMAT TSVWithNamesAndTypes");

echo $a->getFormat(); // return (wrong value) TSVWithNames
`

Suggested fixes: src/Query/Query.php line 55 and 56 shoud changes as follow:
`        $supportFormats =
             "FORMAT\\s+TabSeparatedWithNamesAndTypes|FORMAT\\s+TabSeparatedWithNames|FORMAT\\s+TabSeparatedRaw|FORMAT\\s+TabSeparated|FORMAT\\s+TSVWithNamesAndTypes|FORMAT\\s+TSVWithNames|FORMAT\\s+TSVRaw|FORMAT\\s+TSV|FORMAT\\s+TSKV|FORMAT\\s+JSONCompact|FORMAT\\s+JSONEachRow|FORMAT\\s+BlockTabSeparated|FORMAT\\s+CSVWithNames|FORMAT\\s+CSV|FORMAT\\s+JSON|FORMAT\\s+Vertical";`

**Comment by isublimity** [comment]
build 1.3.2
