### ISSUE TITLE
Do not use keep-alive or reuse them across requests

### ISSUE THREAD

**Issue by Slind14** [smi2/phpClickHouse#109]
Hi there,
the current implementation of curl is keeping connections open and not reusing them across requests. This is clocking up connections with TIME_WAIT:

```
netstat -tan | awk '$5 ~ /:813/ {print $6}' | sort | uniq -c | sort -n
      1 FIN_WAIT2
      2 ESTABLISHED
  92272 TIME_WAIT
```

I would suggest to avoid using keep-alive or switching to something like pecl-http which is using a shared pool of connections across requests according to this: https://stackoverflow.com/questions/41623271/php-and-persistent-http-connections/41643667#41643667

**Comment by isublimity** [comment]
I think you need to disable keepAlive by default.

https://github.com/smi2/phpClickHouse/blob/b661da0d6e3e3fed6aabf18a5b4c422ff0e32deb/src/Transport/Http.php#L198


https://github.com/smi2/phpClickHouse/blob/6a3e65777fdcd3d4d92cde5564fdac355d8620e1/src/Transport/CurlerRequest.php#L345

**Comment by Slind14** [comment]
We migrated to pecl_http with custom post requests.

**Comment by isublimity** [comment]
build 1.3.2
