### ISSUE TITLE
Can not use numbers() function in read requests

### ISSUE THREAD

**Issue by stanislav-reshetnev** [smi2/phpClickHouse#110]
https://github.com/smi2/phpClickHouse/blob/c715a281959a8788cc91f4a95864e4c704dcbf3d/src/Transport/Http.php#L389

Why do you forcing rewrite **readonly** option for read operations? It does not allow to use table functions like _numbers()_. So, **readonly** option can be 2 as well.

**Comment by isublimity** [comment]
build 1.3.2
