### ISSUE TITLE
ValueFormatter should be in include.php

### ISSUE THREAD

**Issue by NataliyaPavlova** [smi2/phpClickHouse#111]
you probably better add
    include_once __DIR__ . '/src/Quote/ValueFormatter.php'; 
in include.php. 
Its abscence leads to fatal error with using  insertAssocBulk and insert (see stack trace)

![stack_trace](https://user-images.githubusercontent.com/32094455/54258217-03463880-4573-11e9-8d88-cb7d9ad746a9.png)

**Comment by isublimity** [comment]
After some time `include.php` is deprecated.
Use autoload by composer.

**Comment by isublimity** [comment]
resolve in last buld
