### ISSUE TITLE
Cannot pass function call to INSERT queries

### ISSUE THREAD

**Issue by FloatingMaster** [smi2/phpClickHouse#112]
You can't simply pass function call (like IPv4StringToNum) to Client->insert because StrictQuoteLine escapes any string values. Workaround is to use class with __toString method() or write complete query to Client->write. 

Maybe you could provide some api to leave fileds unescaping or allow to use custom formatters?

**Comment by isublimity** [comment]
Try build 1.3.2 
See https://github.com/smi2/phpClickHouse/pull/106
