### ISSUE TITLE
about the  --input_format_allow_errors_num AND --input_format_allow_errors_ratio

### ISSUE THREAD

**Issue by gclinux** [smi2/phpClickHouse#114]
clickhouse-client --input_format_allow_errors_num=1 \
--input_format_allow_errors_ratio=0.1 \
--query="INSERT INTO test.formats_test FORMAT TSV"

how to use this two arg in php

**Comment by isublimity** [comment]
Try use settings https://github.com/smi2/phpClickHouse#settings

like 

```php
// apply array method
$db->settings()->apply([
    'input_format_allow_errors_ratio' => 0.1,
    'input_format_allow_errors_num' => 111
]);

```
