### ISSUE TITLE
select error - Can`t find meta

### ISSUE THREAD

**Issue by n00bik** [smi2/phpClickHouse#115]
Hello.

I try to check if records already exist, and get error = "An exception occurred while executing 'SELECT 1 dupl FROM payments WHERE order_id= :order_id AND appid= :appid LIMIT 1' with params ["xxx=:1:11", "yyy-Amazon"]:\n\nCan`t find meta"}

My code:
$stmt = $conn->prepare('SELECT 1 dupl FROM payments WHERE order_id= :order_id AND appid= :appid LIMIT 1'); $stmt->bindValue('order_id', $order_id); $stmt->bindValue('appid', $j->app_id); $stmt->execute(); while ($row = $stmt->fetch()) { file_put_contents('ch_dupl_' . date('Y-m-d') . '_' . $tbl . '_' . $j->app_id . '_' . uniqid() . '.json', json_encode($j)); return true; }

My table structure:
CREATE TABLE default.payments ( cohort Date, installdatetime DateTime, attributedtouchtime Nullable(DateTime), ... appid String, ... order_id String, ... ) ENGINE = MergeTree() PARTITION BY cohort ORDER BY appid SETTINGS index_granularity = 8192; 

Thank you in advance!

**Comment by 2ur1st** [comment]
Hi
You are trying to use PHP PDO for work with **ClickHouse**? **It's not correct.**
I recommend you to read **the documentation**

**Comment by n00bik** [comment]
I use symfony with this driver https://github.com/FriendsOfDoctrine/dbal-clickhouse. I can do insert with this, but any select statment return "Can`t find meta"

**Comment by isublimity** [comment]
Try write issue on FriendsOfDoctrine/dbal-clickhouse

I'm don't know how use phpCh in symfony ;(
