### ISSUE TITLE
Drop UInt32 Partition

### ISSUE THREAD

**Issue by alberto-bottarini** [smi2/phpClickHouse#120]
I've got some partition as UInt32 type.
Using `dropPartition` method I got `Type mismatch in IN or VALUES section. Expected: UInt32. Got: String`.

Looking through the code I found a `trim` on the partition name forces a php int to become a string.

It this trim really useful?

**Comment by isublimity** [comment]
dropPartition is deprecated function.
I forgot to remove from readme 
sorry

**Comment by alberto-bottarini** [comment]
In favor of what?

**Comment by isublimity** [comment]
I`m not full test code in lib 
I recommend just taking this code to yourself
```
public function dropPartition(string $dataBaseTableName, $partition_id)
    {


        $this->settings()->set('replication_alter_partitions_sync', 2);
        $state = $this->write('ALTER TABLE {dataBaseTableName} DROP PARTITION :partion_id',
            [
                'dataBaseTableName' => $dataBaseTableName,
                'partion_id'        => $partition_id,
            ]);

        return $state;
    }
```
