### ISSUE TITLE
SQL Injection / Prepared Statements

### ISSUE THREAD

**Issue by karlbuckland** [smi2/phpClickHouse#123]
I'm looking through the code and the Clickhouse docs and I'm trying to find out if I need to worry about SQL Injection at all, and whether or not I can use prepared statements. Specifically, the data I'm looking to insert into Clickhouse has come from the browser, so ensuring that SQL injection isn't possible is clearly quite important.

From what I can read, it seems that other languages (Python, Go, etc) have support for prepared statements when working with Clickhouse. phpClickHouse does not - although I can see that it quotes and formats values before they are used in SQL queries.

Is SQL injection something to worry about, or is this handled in the library?

**Comment by isublimity** [comment]
library not provided full protection `SQL Injection`.
You have to take care of pasting your data in advance.
