### ISSUE TITLE
The error of array saving 

### ISSUE THREAD

**Issue by mescheryakova-na** [smi2/phpClickHouse#127]
When you need to save an array of data whose elements contain characters that need to be escaped, the data is escaped twice.
For example:
An origin array contains the strings: aaaa\\, bbb'b.
The insert sql contains the value ['aaa\\\\\\\\', 'bbb\\\'b'] instead of ['aaa\\\\', 'bbb\\'b']

**Comment by isublimity** [comment]
thanks for the error sent
Sorry long fix -)
