### ISSUE TITLE
Function insertBatchFiles doesn't work in console application

### ISSUE THREAD

**Issue by AlexChirkov** [smi2/phpClickHouse#137]
Function insertBatchFiles doesn't work in console application. I got an error: "ERROR:
No URL set!". Web application is ok.

**Comment by isublimity** [comment]
Try use verbose mode to find problem

**Comment by AlexChirkov** [comment]
-----------BODY REQUEST----------
------END--------
-----------BODY REQUEST----------
Here is an output:

------END--------
-----------BODY REQUEST----------
------END--------
-----------BODY REQUEST----------
------END--------
-----------BODY REQUEST----------
------END--------
* No URL set!
* No URL set!
* No URL set!
* No URL set!
* No URL set!

Exception 'ClickHouseDB\Exception\QueryException' with message 'No URL set!'

in C:\webserver\web\analytic\vendor\smi2\phpclickhouse\src\Statement.php:183

Stack trace:
#0 C:\webserver\web\analytic\vendor\smi2\phpclickhouse\src\Client.php(613): ClickHouseDB\Statement->error()
#1 C:\webserver\web\analytic\helpers\LogicModelLoadHelper.php(136): ClickHouseDB\Client->insertBatchFiles()

**Comment by AlexChirkov** [comment]
In the web application:

-----------BODY REQUEST----------
------END--------
-----------BODY REQUEST----------
------END--------
-----------BODY REQUEST----------
------END--------
-----------BODY REQUEST----------
------END--------
-----------BODY REQUEST----------
------END--------
use time:7.05
/app/storage/0.csv => {"size_upload":"2.51 MB","upload_content":"-1 bytes","speed_upload":"3.01 Mbps","time_request":7.005}
/app/storage/1.csv => {"size_upload":"2.52 MB","upload_content":"-1 bytes","speed_upload":"3.09 Mbps","time_request":6.829}
/app/storage/2.csv => {"size_upload":"2.52 MB","upload_content":"-1 bytes","speed_upload":"3.01 Mbps","time_request":6.999}
/app/storage/3.csv => {"size_upload":"2.52 MB","upload_content":"-1 bytes","speed_upload":"3.02 Mbps","time_request":6.987}
/app/storage/4.csv => {"size_upload":"2.52 MB","upload_content":"-1 bytes","speed_upload":"3.03 Mbps","time_request":6.962}

**Comment by isublimity** [comment]
I think php(curl) cant read file before insert.
Check file exists & file permission
Try file_get_content($myfile) 
Try my example code https://github.com/smi2/phpClickHouse/blob/master/example/exam03_batch_insert.php

**Comment by AlexChirkov** [comment]
File exist and permission is ok. Example not working too. Same error message(
