### ISSUE TITLE
INSERT FORM CSV Too Slow

### ISSUE THREAD

**Issue by jiaoyang3** [smi2/phpClickHouse#142]
`insertBatchFiles($table, $file_data_names)`
csv file size=85m，row=100000

**used 2.5s**

but used curl request need **0.7s**
`curl -i -v -X POST --data-binary @1.csv 'http://host:8123/?extremes=0&readonly=0&max_execution_time=60&enable_http_compression=1&database=&query=INSERT%20INTO%20test_order_detail_tmp%20FORMAT%20CSV%20' --header 'X-ClickHouse-User:' --header 'X-ClickHouse-Key:'`

why？

**Comment by lizhichao** [comment]
It is faster to use TCP mode to stream write

**Comment by isublimity** [comment]
Use streamWrite - this more fast
