### ISSUE TITLE
selectAsync() does not work with Symfony console commands

### ISSUE THREAD

**Issue by bun4uk** [smi2/phpClickHouse#143]
For some reason, select/executeAsync() don't work with Symfony commands. 
The script is just not responding.
I tried to debug `CurlerRolling::execLoopWait()` methods and `($this->countActive() + $this->countPending())` is always bigger than 0;
Probably it caused somehow by the buffered output of Symfony command.
Have you ever faced this issue? Is there a way how to solve it?

**Comment by isublimity** [comment]
I haven't worked with Symfony, but you are the first to write about it.
My colleagues who use symfony+async have never encountered such a problem.

Try a simple code like this: 

```
for ($f=0;$f<1000;$f++)
{
    $list[$f]=$db->selectAsync('SELECT {num} as num',['num'=>$f]);
}
$db->executeAsync();
for ($f=0;$f<1000;$f++)
{
    $c=$list[$f];

    echo $f."\t";
    $ret='-';
    try{
        $ret=$c->fetchOne('num');
    }catch (Exception $e)
    {

    }


    echo "$ret\n";
}
```

**Comment by isublimity** [comment]
`is always bigger than 0;` - show some task not get/receive answer from CH
