### ISSUE TITLE
Cluster SELECT * FROM system.replicas

### ISSUE THREAD

**Issue by isublimity** [smi2/phpClickHouse#15]
Если запрашивать все столбцы, то таблица может работать слегка медленно, так как на каждую строчку делается несколько чтений из ZK.

Если не запрашивать последние 4 столбца (log_max_index, log_pointer, total_replicas, active_replicas), то таблица работает быстро.

**Comment by alexey-milovidov** [comment]
Да, там такая логика в коде.

**Comment by isublimity** [comment]
Добавил ф-цию Cluster->setSoftCheck(true) 

Если true - то не проверяются log_max_index, log_pointer, total_replicas, active_replicas)
