### ISSUE TITLE
How to prevent the SQL Injection with this lib 

### ISSUE THREAD

**Issue by apausepi** [smi2/phpClickHouse#151]
Are there a solution like PDO::setParameter(..) ?

**Comment by simPod** [comment]
I have investigated that for https://github.com/simPod/PhpClickHouseClient and I recommend subscribing https://github.com/ClickHouse/ClickHouse/issues/8842

**Comment by isublimity** [comment]
I`m try implement 

```
curl -X POST -F 'query=select {p1:UInt8} + {p2:UInt8}' -F "param_p1=3" -F "param_p2=4" 'http://default:default@localhost:8123/'
7
```

**Comment by devicenull** [comment]
Was this implemented?  While I can use `{x}` within a query, it doesn't appear to get escaped - and just a dumb string replacement happens, leading to sqli vulns

I'm doing
```
$db->select('select * from test where ID={ID}', ['ID' => 1]);
```

**Comment by supun-io** [comment]
We wrote [hyvor/clickhouse-php](https://github.com/hyvor/clickhouse-php) for this exact use case. It's a very basic wrapper around Clickhouse's HTTP interface with params support.

**Comment by donatascn** [comment]
I would also like to know if there are plans to implement it.

**Comment by antanasja** [comment]
I have tested the solution manually and can confirm it is working.

**Comment by antanasja** [comment]
Added support for arrays.

**Comment by antanasja** [comment]
Can we get a new release regarding this?

**Comment by isublimity** [comment]
pub 1.5.1
