### ISSUE TITLE
Parse request timeout error

### ISSUE THREAD

**Issue by ponikrf** [smi2/phpClickHouse#152]
Hi. 
Version 1.3.10

I get this error if set request clickhouse timeout 1.5

```
ClickHouseDB\Exception\QueryException: 
HttpCode:400 ; 
;
Code: 27, e.displayText() =
DB::ParsingException: Cannot parse input: expected 'eof' before: '.5' (version 21.2.3.15 (official build))
```

if i set timeout 1 or 2... everything works

Previously, the option with setting a timeout to float worked. Perhaps someone will face the same problem.

**Comment by isublimity** [comment]
Yes my mistake 

In source code CH: 
https://github.com/ClickHouse/ClickHouse/blob/20.8/src/Core/Settings.h#L52
```
 M(Seconds, max_execution_time, 0, "", 0) \
```

Change type to Int

**Comment by isublimity** [comment]
Thx!
