### ISSUE TITLE
Port 3003 is for clickhouse-client program

### ISSUE THREAD

**Issue by ruibin** [smi2/phpClickHouse#159]
context:{"data":["2021-11-03"],"throwable":{"className":"ClickHouseDB\\Exception\\QueryException","file":"vendor/smi2/phpclickhouse/src/Statement.php(182)","code":400,"msg":"HttpCode:400 ;  ;Port 3003 is for clickhouse-client program.\r\nYou must use port 3002 for HTTP.\r\n"}}

**Comment by isublimity** [comment]
Use pot 3002 ;)

**Comment by ruibin** [comment]
I can't find where is the configuration. Do you mean this: https://clickhouse.com/docs/en/operations/configuration-files/ ? What is the configuration key?

**Comment by ruibin** [comment]
I can't find where is the configuration. Do you mean this: https://clickhouse.com/docs/en/operations/configuration-files/ ? What is the configuration key?

**Comment by ruibin** [comment]
Sorry for this delay. I migrated some code. And the package conmunicate clickhouse server through TCP Mode. So I change the port to http port then is works
