### ISSUE TITLE
Extremes in readonly mode

### ISSUE THREAD

**Issue by SerafimArts** [smi2/phpClickHouse#16]
```
PHP Fatal error:  Uncaught ClickHouseDB\DatabaseException: 
    Cannot override setting (extremes) in readonly mode
IN:show databases 
    FORMAT JSON in /home/u/api/vendor/smi2/phpclickhouse/src/Statement.php:166
```

Maybe can u do not send extremes query arg if this does not set?

Same with: `max_execution_time`, `enable_http_compression` and `readonly`

**Comment by isublimity** [comment]
Странная ошибка, а пример кода можете дать ( последовательность действий ) 
пробую 
```
$db->enableExtremes(true)->enableHttpCompression();
print_r($db->showDatabases());
```
Все ок, может у пользователя ограничения ?

**Comment by SerafimArts** [comment]
@isublimity я про ограничения пользователя и говорю. Либа вообще перестаёт работать, если акк ридонли =)

**Comment by isublimity** [comment]
Возможно не очень "чисто" получилось 

https://github.com/smi2/phpClickHouse/commit/89cbbe7ddd08fc9ee1ba43a6786d1ec4f9e36986

**Comment by SerafimArts** [comment]
Я думаю, что проще было бы просто игнорить null-значения в конфигах, т.е. true - передаётся `1`, для фолс соответсвенно `0`, а все null тупо игнорятся.
