### ISSUE TITLE
How can I make SQL request OPTIMIZE TABLE tableName DEDUPLICATE with the lib?

### ISSUE THREAD

**Issue by Morgunov-Vitaly** [smi2/phpClickHouse#160]
Hi!
Could you suggest me the way to make SQL request OPTIMIZE TABLE tableName DEDUPLICATE with this lib?
I use ReplacingMergeTree engine but I want to make  OPTIMIZE request after insertion from CSV file.

**Comment by isublimity** [comment]
```php

$db->write("....");


```
