### ISSUE TITLE
Query logging

### ISSUE THREAD

**Issue by milosb793** [smi2/phpClickHouse#165]
Hey all,

I'm trying to figure out how does the `log_queries` setting is working. Does the `select()` returns query as string, or queries are getting saved to some CH table, or something else? Is it possible to have it log queries to some log file?

Thanks in further!

P.S. awesome library, thanks!

**Comment by isublimity** [comment]
https://clickhouse.com/docs/en/operations/system-tables/query_log

When i`m need select all PHP client query from server like this: 

```

SELECT * FROM
system.query_log
WHERE client_name like '%php%'
LIMIT 40

```

**Comment by isublimity** [comment]
log_queries - force call CH write to log query

**Comment by milosb793** [comment]
Thanks @isublimity!
