### ISSUE TITLE
Cannot use socket_timeout 

### ISSUE THREAD

**Issue by suchen9209** [smi2/phpClickHouse#185]
some big query ,can run in server
it will be timeout when you select by sql in code,
clickhouse give "socket_timeout=60000" ,like ''jdbc:clickhouse://127.0.0.1:8123/default?socket_timeout=60000'
but i can't use this config in this project

**Comment by isublimity** [comment]
You try ? 
```php

$db->settings()->set('xxxx',yyy);

```
