### ISSUE TITLE
[ClickHouseDB\QueryException] connect() timed out!

### ISSUE THREAD

**Issue by magnum-ferox** [smi2/phpClickHouse#19]
Привет, делаю в бесконечном цикле кучу селектов и инсертов и рандомно (может через 5 секунд, а может через 10 минут) вылетает ексепшен.
Причём поиском по коду такой фрагмент месаджа нигде не находится. Так что за эксепшен такой, о каком таймауте речь и как его увеличить?

```
  [ClickHouseDB\QueryException]
  connect() timed out!
```

```
Exception trace:
 () at /var/www/vendor/smi2/phpclickhouse/src/Statement.php:178
 ClickHouseDB\Statement->error() at /var/www/vendor/smi2/phpclickhouse/src/Transport/Http.php:426
 ClickHouseDB\Transport\Http->write() at /var/www/vendor/smi2/phpclickhouse/src/Client.php:228
```

```
        $config = [
            'host' => env('DB_CLICKHOUSE_HOST'),
            'port' => env('DB_CLICKHOUSE_PORT'),
            'username' => env('DB_CLICKHOUSE_USERNAME'),
            'password' => env('DB_CLICKHOUSE_PASSWORD')
        ];

        $Clickhouse = new Client($config);
        $Clickhouse->database('db');
```

**Comment by isublimity** [comment]
Ошибка может возникать в нескольких местах: Клиент не может подключиться CH 
* из за сети 
* из за DNS 
* Отправляется не корректный запрос который возращает 100 continue


Попробовать увеличить максимальное время запроса и ожидания 
```php
$db->setTimeout(10)
```

Перед каждым запросом пробовать ставить свою настройку setConnectTimeOut
```php
$db->setConnectTimeOut(5);
```


Включить режим Verbose и отловить ошибку 
```php 
$db->verbose();
```

Используется версия master или из composer, если  composer попробуйте из ветки master
