### ISSUE TITLE
How to check insertBatchFiles is finished

### ISSUE THREAD

**Issue by jeanatpi** [smi2/phpClickHouse#198]
Hi,

I'm using insertBatchFiles to insert multiple CSV files in 1 go.

Looking at the code, I'm not sure there's a way to check insert has been completed. Can you clarify / help?

**Comment by isublimity** [comment]
insertBatchFiles - return Statement[]

some like this

```php 

$dd=$db->insertBatchFiles(...)
foreach ($dd as $StatementX)
{
   $StatementX->isError()
   print_r($StatementX->info()....)
}

```
