### ISSUE TITLE
Method  `setConnectTimeOut` doesn't exist

### ISSUE THREAD

**Issue by vetinary** [smi2/phpClickHouse#20]
Method `setConnectTimeOut` mentioned in readme file is not implemented in source code. Actually, now there is no way to change the timeout setting for cURL, which is 1 second by default.
There is method `connectTimeOut` implemented in CurlerRequest.php, but it has no interface in Client nor Http classes to make it possible to affect the connection timeout.

**Comment by isublimity** [comment]
Try use master branch - git clone or git submodule.

Composer release not have last commits

**Comment by vetinary** [comment]
Why don't you just push it to a new release?

**Comment by isublimity** [comment]
I forgot build the last master 
I will try to gather today or tomorrow

**Comment by isublimity** [comment]
public

**Comment by isublimity** [comment]
https://github.com/smi2/phpClickHouse/releases/tag/0.17.02
