### ISSUE TITLE
Using insertBatchFiles with CSVWithNamesAndTypes is not possible

### ISSUE THREAD

**Issue by jeanatpi** [smi2/phpClickHouse#200]
I'd like to use insertBatchFiles with CSVWithNamesAndTypes and it is not possible at the moment because of SUPPORTED_FORMATS const.

const SUPPORTED_FORMATS = ['TabSeparated', 'TabSeparatedWithNames', 'CSV', 'CSVWithNames', 'JSONEachRow'];

Is this lib still maintain and would it be possible to add this CSVWithNamesAndTypes + TSVWithNamesAndTypes ?

If I can contribute, let me know.

**Comment by isublimity** [comment]
Please test - must be work

**Comment by jeanatpi** [comment]
I'll give a try. Thanks!

**Comment by jeanatpi** [comment]
@isublimity I can confirm, it works!
