### ISSUE TITLE
Php syntax error in php ^7.3

### ISSUE THREAD

**Issue by russelomua** [smi2/phpClickHouse#206]
`int|float` syntax does not supported by `php 7.3` which is defined in `composer.json`
https://github.com/smi2/phpClickHouse/blob/3e4de6e81e704283a5200355654d6a5bc2c26a75/src/Client.php#L188

https://github.com/smi2/phpClickHouse/blob/3e4de6e81e704283a5200355654d6a5bc2c26a75/composer.json#L16

Please remove support of `php 7.3` for this release or use supported syntax features.
TNX.

**Comment by isublimity** [comment]
Thx for support 
I`m release new version
