### ISSUE TITLE
Search with cyrillic symbols in 'LIKE' returns no results

### ISSUE THREAD

**Issue by vetinary** [smi2/phpClickHouse#21]
I have a query, which has condition `concat(name, ' ', last_name) LIKE '%some_string%'` and I have found out, that if **some_string** has cyrillic symbols, the result has no rows. But when I use the same query in clickhouse-client, it returns correct results. 
Such behavior makes me think, that there is some problem with the body of request somewhere in phpClickHouse. I tried to debug it myself but have had no luck in detecting a place with the issue.

**Comment by isublimity** [comment]
Try use cl->verbose(true) 

php unit говорит что все отлично )

**Comment by vetinary** [comment]
У меня всё же отмечено очень странное поведение при использовании русского языка. Вот пример выполнения запроса через phpClickHouse и вывод полученного результата:
![2017-03-09 19 21 16](https://cloud.githubusercontent.com/assets/1561945/23759399/2154b5ea-0506-11e7-94c6-9ae8dceeaa8f.png)

Вот тот же самый запрос, но выполненный из clickhouse-client:
![2017-03-09 19 21 59](https://cloud.githubusercontent.com/assets/1561945/23759457/4fa3c828-0506-11e7-837e-e2c2bf178460.png)

Как видно, результаты отличаются. И это случайность, что вообще какой-то результат вернулся: обычно при кириллице просто ничего нет в ответе.
Уже даже не знаю, в какую сторону копать. Может, cURL что-то с UTF-8 при отправке запроса делает? Просто это единственное, на что можно подумать, потому как без кириллицы всё работает великолепно.

**Comment by isublimity** [comment]
Попробуйте с verbose() , добавил сам запрос который отравляется curl-om 

https://github.com/smi2/phpClickHouse/commit/ab32ffb8fc1989f9b384cbeb820776c2fa451507#diff-9463b110dd9cddf350126a240ba5dab8R693

Пример : 
```
* Rebuilt URL to: http://192.168.1.20:8123/?extremes=0&readonly=1&max_execution_time=20&enable_http_compression=0&database=default
* Hostname 192.168.1.20 was found in DNS cache
*   Trying 192.168.1.20...
* Connected to 192.168.1.20 (192.168.1.20) port 8123 (#0)
* Server auth using Basic with user 'default'
> POST /?extremes=0&readonly=1&max_execution_time=20&enable_http_compression=0&database=default HTTP/1.1
Host: 192.168.1.20:8123
Authorization: Basic ZGVmYXVsdDo=
User-Agent: smi2/PHPClickHouse/client
Cache-Control: no-cache, no-store, must-revalidate
Expires: 0
Pragma: no-cache
Connection: Keep-Alive
Keep-Alive: 60
Content-Type: application/json, text/javascript; charset=utf-8
Accept: application/json, text/javascript, */*; q=0.01
Content-Length: 92

* upload completely sent off: 92 out of 92 bytes
< HTTP/1.1 200 OK
< Date: Thu, 09 Mar 2017 17:13:27 GMT
< Connection: Keep-Alive
< Content-Type: application/json; charset=UTF-8
< Transfer-Encoding: chunked
<
* Closing connection 0
.
-----------BODY REQUEST----------
SELECT  url_hash FROM summing_url_views WHERE like(url_hash,'%Русский%')  FORMAT JSON
------END--------
```


Если визуально все ок -> попробуйте через консольный curl типа 
curl -X POST -v .... 


Еще идея посмотреть  php -i | grep mb
У меня сейчас так 
```
mbstring.detect_order => no value => no value
mbstring.encoding_translation => Off => Off
mbstring.func_overload => 0 => 0
mbstring.http_input => no value => no value
mbstring.http_output => no value => no value
mbstring.http_output_conv_mimetypes => ^(text/|application/xhtml\+xml) => ^(text/|application/xhtml\+xml)
mbstring.internal_encoding => no value => no value
mbstring.language => neutral => neutral
mbstring.strict_detection => Off => Off
mbstring.substitute_character => no value => no value
```


Вариант еще заменить like на WHERE last_name="ЧЯЧСМ" - будет не будет работать ...

**Comment by vetinary** [comment]
Приношу свои извинения и прошу простить меня за украденное у Вас время. 
В процессе попытки воспроизведения проблемы, выяснил, что clickhouse-client работает с одной базой, а web-приложение — с другой. Раньше и то и другое работало с одним набором данных, но у меня совершенно вылетело из головы, что для web я не так давно изменил настройки соединения.

**Comment by isublimity** [comment]
Бывает) 
Дополнительный юнит тест и доп. инфа в verbose() - драйверу на пользу)

**Comment by vetinary** [comment]
Кстати, verbose() ничего не выводит на данный момент. По крайней мере, та версия, которая в релизе. До своей ошибки я дошёл, когда через консольный curl воспроизводил проблему.
