### ISSUE TITLE
Hardcoded http protocol or necessary add https transport

### ISSUE THREAD

**Issue by rasl** [smi2/phpClickHouse#24]
I configured my clickhouse server http connection with ssl option, i.e. I try connect to https://localhose:8443/
it's fail like: 
'Recv failure: Connection reset by peer'
https://github.com/smi2/phpClickHouse/blob/master/src/Transport/Http.php#L116

**Comment by isublimity** [comment]
Try last master 


add in commit: https://github.com/smi2/phpClickHouse/commit/8f46eca670113bccf38bcc051b94fd4d9a1ca5e2

example: https://github.com/smi2/phpClickHouse/blob/master/example/exam21_httpS.php

**Comment by rasl** [comment]
The solutions looks like working, but I expected more complexity solution like https transport.
Anyway, thanks for the quick response.
