### ISSUE TITLE
Bug: Binding array values

### ISSUE THREAD

**Issue by ilya-tikhomirov** [smi2/phpClickHouse#25]
Replace binding values from largest key to smallest.
To avoid wrong replacing.

Example:
```
[
   ':key1' => 100500,
   ':key123' => 500100,
]
```

`:key1, :key123`

Expected:
`100500, 500100`

Returned:
`100500, 10050023`

**Comment by isublimity** [comment]
I try change code 

https://github.com/smi2/phpClickHouse/blob/master/src/Query/Degenerations/Bindings.php#L66

**Comment by isublimity** [comment]
try 

https://github.com/smi2/phpClickHouse/commit/10081b8e78698dc6bd3f9ba0329f32c3eb8393ed
