### ISSUE TITLE
PHP-alpine: При включение компрессии запись в БД валится

### ISSUE THREAD

**Issue by 2ur1st** [smi2/phpClickHouse#32]
При включение компрессии
`$client->enableHttpCompression(true);` 

Вываливается ошибка:
`Warning: curl_setopt_array(): cannot cast a filtered stream on this system in /var/www/analytics/vendor/smi2/phpclickhouse/src/Transport/CurlerRequest.php on line 695
`

Думаю что проблема в том, что для загрузки файла используется ключ curl CURLOPT_SAFE_UPLOAD который в версии php 7 удален. 
Есть ли какие патчи на эту багу?

**Comment by isublimity** [comment]
Проверил в 
Runtime:       PHP 7.0.22-0ubuntu0.16.04.1
Тесты проходит ( 


Попробуйте сделать тест как тут https://github.com/smi2/phpClickHouse/blob/master/example/exam03_batch_insert.php

который валится

**Comment by isublimity** [comment]
Ф-ция которая отвечает за заливку данных 
https://github.com/smi2/phpClickHouse/blob/master/src/Transport/CurlerRequest.php#L221
Попробуйте у себя убрать safe 
или проверьте `php -i | grep ZLib`

**Comment by 2ur1st** [comment]
Я использую докер, и чаще всего использую легковесные контейнеры 7.1-fpm-alpine.
Именно в этих контейнерах тесты не проходят. Для контейнеров на базе debian:jessie такой проблемы нет.
У всех контейнеров модуль для работы с сжатыми файлами есть и он включен

**Comment by isublimity** [comment]
Подтвердил проблема только в alpine 

FALSE: 
```
#7.1-alpine
docker run -it --rm --name my-running-script -v "$PWD":/sites/phpClickHouse -w /sites/phpClickHouse php:7.1-alpine php example/exam03_batch_insert.php
# 7.2-alpine3.6
docker run -it --rm --name my-running-script -v "$PWD":/sites/phpClickHouse -w /sites/phpClickHouse php:7.2-alpine3.6 php example/exam03_batch_insert.php
```


OK :
```
docker run -it --rm --name my-running-script -v "$PWD":/sites/phpClickHouse -w /sites/phpClickHouse php:7.1 php example/exam03_batch_insert.php

```


Проблема в php-src : https://github.com/php/php-src/search?utf8=%E2%9C%93&q=php_stream_is_filtered&type=




Возможно связанные проблемы : https://github.com/docker-library/php/issues/504

**Comment by isublimity** [comment]
Work for php:7.2-alpine3.7
