### ISSUE TITLE
Problems with "Not set `FORMAT JSON` if set FORMAT in sql"

### ISSUE THREAD

**Issue by yurganov** [smi2/phpClickHouse#36]
Hi.

I've got query like "select **format**_id from ...", and "`$query->setFormat('JSON');`" in `prepareSelect` function.

Because of the commit "bc810d0", such queries had been broken.

Suggested solution:

Change the line 55 to `if (stripos($this->sql, ' FORMAT ') < 1) {`

Maybe there is more elegance solution, such as regexp "`FORMAT\s(\w)*$`", but I am not sure about perfomance.

**Comment by isublimity** [comment]
Try 0.17.12.1


https://github.com/smi2/phpClickHouse/commit/4b0305b8d78f466d96af52df0e02acea19253861#diff-44033e4828daf43ec4fd22dc123a8c5f
