### ISSUE TITLE
drop partition error

### ISSUE THREAD

**Issue by molchanov1983** [smi2/phpClickHouse#37]
Hello. I have an error during removing partition
Message= String is too long for Date: '2017-12-26'
IN:ALTER TABLE operation_log DROP PARTITION '\'2017-12-26\''

Partition list :
<pre>Array
(
    [20171226_10_10_0] => Array
        (
            [partition] => '2017-12-26'
            [name] => 20171226_10_10_0
            [active] => 1
            [marks] => 1
            [marks_size] => 144
            [rows] => 1
            [bytes] => 1311
            [modification_time] => 2017-12-26 17:06:31
            [remove_time] => 0000-00-00 00:00:00
            [refcount] => 1
            [min_date] => 2017-12-26
            [max_date] => 2017-12-26
            [min_block_number] => 10
            [max_block_number] => 10
            [level] => 0
            [primary_key_bytes_in_memory] => 4
            [primary_key_bytes_in_memory_allocated] => 4096
            [database] => netflow
            [table] => operation_log
            [engine] => MergeTree
        )

    [20171226_9_9_0] => Array
        (
            [partition] => '2017-12-26'
            [name] => 20171226_9_9_0
            [active] => 1
            [marks] => 1
            [marks_size] => 144
            [rows] => 1
            [bytes] => 1311
            [modification_time] => 2017-12-26 17:06:30
            [remove_time] => 0000-00-00 00:00:00
            [refcount] => 1
            [min_date] => 2017-12-26
            [max_date] => 2017-12-26
            [min_block_number] => 9
            [max_block_number] => 9
            [level] => 0
            [primary_key_bytes_in_memory] => 4
            [primary_key_bytes_in_memory_allocated] => 4096
            [database] => netflow
            [table] => operation_log
            [engine] => MergeTree
        )

    [20171226_8_8_0] => Array
        (
            [partition] => '2017-12-26'
            [name] => 20171226_8_8_0
            [active] => 1
            [marks] => 1
            [marks_size] => 144
            [rows] => 1
            [bytes] => 1311
            [modification_time] => 2017-12-26 17:06:29
            [remove_time] => 0000-00-00 00:00:00
            [refcount] => 1
            [min_date] => 2017-12-26
            [max_date] => 2017-12-26
            [min_block_number] => 8
            [max_block_number] => 8
            [level] => 0
            [primary_key_bytes_in_memory] => 4
            [primary_key_bytes_in_memory_allocated] => 4096
            [database] => netflow
            [table] => operation_log
            [engine] => MergeTree
        )

    [20171226_7_7_0] => Array
        (
            [partition] => '2017-12-26'
            [name] => 20171226_7_7_0
            [active] => 1
            [marks] => 1
            [marks_size] => 144
            [rows] => 1
            [bytes] => 1311
            [modification_time] => 2017-12-26 17:06:28
            [remove_time] => 0000-00-00 00:00:00
            [refcount] => 1
            [min_date] => 2017-12-26
            [max_date] => 2017-12-26
            [min_block_number] => 7
            [max_block_number] => 7
            [level] => 0
            [primary_key_bytes_in_memory] => 4
            [primary_key_bytes_in_memory_allocated] => 4096
            [database] => netflow
            [table] => operation_log
            [engine] => MergeTree
        )

    [20171226_6_6_0] => Array
        (
            [partition] => '2017-12-26'
            [name] => 20171226_6_6_0
            [active] => 0
            [marks] => 1
            [marks_size] => 144
            [rows] => 1
            [bytes] => 1311
            [modification_time] => 2017-12-26 16:56:50
            [remove_time] => 2017-12-26 17:06:07
            [refcount] => 1
            [min_date] => 2017-12-26
            [max_date] => 2017-12-26
            [min_block_number] => 6
            [max_block_number] => 6
            [level] => 0
            [primary_key_bytes_in_memory] => 4
            [primary_key_bytes_in_memory_allocated] => 4096
            [database] => netflow
            [table] => operation_log
            [engine] => MergeTree
        )

    [20171226_5_5_0] => Array
        (
            [partition] => '2017-12-26'
            [name] => 20171226_5_5_0
            [active] => 0
            [marks] => 1
            [marks_size] => 144
            [rows] => 1
            [bytes] => 1311
            [modification_time] => 2017-12-26 16:56:49
            [remove_time] => 2017-12-26 17:06:07
            [refcount] => 1
            [min_date] => 2017-12-26
            [max_date] => 2017-12-26
            [min_block_number] => 5
            [max_block_number] => 5
            [level] => 0
            [primary_key_bytes_in_memory] => 4
            [primary_key_bytes_in_memory_allocated] => 4096
            [database] => netflow
            [table] => operation_log
            [engine] => MergeTree
        )

    [20171226_4_4_0] => Array
        (
            [partition] => '2017-12-26'
            [name] => 20171226_4_4_0
            [active] => 0
            [marks] => 1
            [marks_size] => 144
            [rows] => 1
            [bytes] => 1311
            [modification_time] => 2017-12-26 16:56:48
            [remove_time] => 2017-12-26 17:06:07
            [refcount] => 1
            [min_date] => 2017-12-26
            [max_date] => 2017-12-26
            [min_block_number] => 4
            [max_block_number] => 4
            [level] => 0
            [primary_key_bytes_in_memory] => 4
            [primary_key_bytes_in_memory_allocated] => 4096
            [database] => netflow
            [table] => operation_log
            [engine] => MergeTree
        )

    [20171226_3_3_0] => Array
        (
            [partition] => '2017-12-26'
            [name] => 20171226_3_3_0
            [active] => 0
            [marks] => 1
            [marks_size] => 144
            [rows] => 1
            [bytes] => 1311
            [modification_time] => 2017-12-26 16:56:47
            [remove_time] => 2017-12-26 17:06:07
            [refcount] => 1
            [min_date] => 2017-12-26
            [max_date] => 2017-12-26
            [min_block_number] => 3
            [max_block_number] => 3
            [level] => 0
            [primary_key_bytes_in_memory] => 4
            [primary_key_bytes_in_memory_allocated] => 4096
            [database] => netflow
            [table] => operation_log
            [engine] => MergeTree
        )

)
Here is my table
CREATE TABLE IF NOT EXISTS `operation_log` (
    `event_date` Date default toDate(time),
    `time` DateTime default  now(),
    `event` String  DEFAULT '',
    `service_name` String  DEFAULT '',
    `runtime` UInt8 DEFAULT 0,
    `service_type` UInt8 DEFAULT 0,
    `response_text` String  DEFAULT '',
    `debug_level` String  DEFAULT '',
    `debug_response_text` String  DEFAULT ''
) ENGINE=MergeTree ORDER BY time PARTITION BY event_date

This is insert query
INSERT INTO operation_log (event, service_name, runtime, service_type, response_text,debug_level,debug_response_text) 
 VALUES ('request', 'Delete Tables', 0, 1, 'Deleted tables: netflow_v4_3,netflow_v4_1', 'normal', '');

This is how to reproduce
1- create table...
2- insert data
3- drop partiton 
4- select * from table => nothing
5 - insert ...
6- select -> some records
7 - drop partition
8 - select => nothing
........
20 - drop partition ..
21- select -> nothing
22- insert 
23 - seelct -> some records

**Comment by isublimity** [comment]
Try replication_alter_partitions_sync=2 

Check my test 
https://github.com/smi2/phpClickHouse/blob/master/example/cluster_08_drop_partitions.php

After add replication_alter_partitions_sync, i not get error  `String is too long` from ClickHouse server

**Comment by molchanov1983** [comment]
Thanks. Will try  to test a little later

**Comment by isublimity** [comment]
Close issue?

**Comment by isublimity** [comment]
ok, i close. if problem please report me
