### ISSUE TITLE
Поддержка NULL в экспорте данных через класс \ClickHouseDB\FormatLine

### ISSUE THREAD

**Issue by 2ur1st** [smi2/phpClickHouse#42]
На данный момент тип NULL заменяется пустой строкой
`'CSV'=>[
            'EnclosureArray'=>'"',
            'EncodeEnclosure'=>'"',
            'Enclosure'=>'"',
            'Null'=>"",
            'Delimiter'=>",",
            'TabEncode'=>false,
        ],`

 думаю есть смысл изменить на \N так как ClickHouse поддерживает NULL
``'CSV'=>[
            'EnclosureArray'=>'"',
            'EncodeEnclosure'=>'"',
            'Enclosure'=>'"',
            'Null'=>"\N",
            'Delimiter'=>",",
            'TabEncode'=>false,
        ],``

**Comment by isublimity** [comment]
В мастере
