### ISSUE TITLE
Не существующий метод: setConnectTimeOut()

### ISSUE THREAD

**Issue by zernopoisk** [smi2/phpClickHouse#44]
Ребята, приветсвтую!
При использовании драйвера **phpClickHouse** возникла необходимость увеличить connection time out, т.е как очень часто появляеться сообщение об ошибке: `"Exception: Connection timed out after 1001 milliseconds".`
На [странице документации](https://github.com/smi2/phpClickHouse) есть код:
`$db->setTimeout(1.5);      // 1500 ms`
`$db->setTimeout(10);       // 10 seconds`
`$db->setConnectTimeOut(5); // 5 seconds`

но, это приводит к ошибке: `Call to undefined method ClickHouseDB\Client::setConnectTimeOut()`.

Поиски соотв. методов в коде не дали результатов.
Обновление к новой версии библиотеки `composer install` тоже не помогло.

Как можно увеличить время соединения к ClickHouse, желательно это делать через конфиг (или setter-метод), чтобы настройка "не слетала" каждый раз при обновлении.

Спасибо!

**Comment by isublimity** [comment]
Добавил тест 
https://github.com/smi2/phpClickHouse/blob/master/tests/00_FormatTest.php#L94

Может у вас не последняя версия из Git ?
