### ISSUE TITLE
Отсутствие документации по развертыванию кластера

### ISSUE THREAD

**Issue by icamys** [smi2/phpClickHouse#45]
В документации отсутствует описание развартывания кластера с несколькими серверами. Неплохой пример есть тут:
https://github.com/the-tinderbox/ClickhouseClient#cluster

**Comment by isublimity** [comment]
Спасибо за замечание) 
так нормально https://github.com/smi2/phpClickHouse/blob/master/README.md#cluster ?

**Comment by icamys** [comment]
Этого пока хватает, спасибо! Мне только кажется, что уместнее раздел с настройкой кластера и его функциями поднять поближе к описанию настройки одного сервера, в раздел [Start](https://github.com/smi2/phpClickHouse/blob/master/README.md#start), чтобы можно было быстро сориентироваться, как разворачивать один сервер и как разворачивать целый кластер.
