### ISSUE TITLE
Создание Query Builder'a

### ISSUE THREAD

**Issue by icamys** [smi2/phpClickHouse#46]
В первую очередь хочу поблагодарить Вас за Ваш труд!

Подскажите пожалуйста, планируется ли создание Query Builder'a Вашей командой?

Дело в том, что такой пакет мог бы существенно упростить интеграцию Вашего клиента с большинством веб-фреймворков и ORM.

Например, сейчас я использую Laravel и Ваш клиент. Написание тестов дается довольно сложно, так как клиент никак не интегрируется с фреймворком. Нет возможности создания моделей и прочих удобств.

Нашел решение в виде сочетания пакетов:

- [the-tinderbox/ClickhouseClient](https://github.com/the-tinderbox/ClickhouseClient) <-- аналог Вашего клиента, реализован используя Guzzle
- [the-tinderbox/ClickhouseBuilder](https://github.com/the-tinderbox/ClickhouseBuilder) <-- Query Builder (которого не хватает) на основе клиента
- [esazykin/laravel-clickhouse](https://github.com/esazykin/laravel-clickhouse) <-- Интеграция с фреймворком на основе Query Builder'a

Недостаток этого решения в том, что там есть доп. зависимости + пакеты похоже заброшены.

**Comment by isublimity** [comment]
Такое делать не планируется, идея клиента минимум доп. ф-ций и зависимостей
