### ISSUE TITLE
Coding standard

### ISSUE THREAD

**Issue by simPod** [smi2/phpClickHouse#52]
Would you be interested in setting up unified code style for this library? Personally, I try to use https://github.com/doctrine/coding-standard in every project as IMHO it is the best CS available. The whole Doctrine project is being migrated to it.

We can add it as a check into Travis after it's added. Having coding standard is great because every contribution to the library is consistent with the rest of the codebase and when automated, we don't have to bother with it during code reviews.

I'm willing to add it in next PR if interested.

**Comment by isublimity** [comment]
Give me time , to approve you prev. PR ;) 

I have problem to apply in my projects where use phpClickHouse. 

I`m not use and like "coding-standard" -- my team reformat "my code" )

But I will try very hard to accept all your remarks
thanks for the work you've done!

**Comment by simPod** [comment]
Yup, doesn't relate, will wait until it's merged ;)

> my team reformat "my code" )

This is exactly why it's cool to have one. 

Will send a proposal afterwards and then it can be decided.

**Comment by simPod** [comment]
Added in https://github.com/smi2/phpClickHouse/commit/4e9dea8d7be6f305faa92b75d89e06dd7265ba44
