### ISSUE TITLE
Use Semantic versioning

### ISSUE THREAD

**Issue by simPod** [smi2/phpClickHouse#62]
This library uses versions like `0.year.month.increment`

It would be better to follow standard and use [Semantic versioning](https://semver.org/) so it can be safely bound in composer, eg. `^0.18` that won't install any breaking changes but only patches.

**Comment by isublimity** [comment]
Yes, this Good idea 

phpClickHouse - ready to V 1.0.0

**Comment by isublimity** [comment]
I will soon publish the 1.0.0 version

**Comment by simPod** [comment]
Cool! Btw would be even cooler to drop support for old php version for v1.0.0 

Security support ending soon anyway http://php.net/supported-versions.php

**Comment by isublimity** [comment]
Public ) 

https://github.com/smi2/phpClickHouse/releases/tag/1.0.0
