### ISSUE TITLE
tablesize - formatReadableSize - not working

### ISSUE THREAD

**Issue by molchanov1983** [smi2/phpClickHouse#63]
Hello
I faced an issue:
$client -> tableSize($table);
http://prntscr.com/jwxtbs
and as a result i got empty response
If i remove formatReadableSize(sum(bytes)) as size, from select quesry - all works ok

**Comment by isublimity** [comment]
Check table name in `$client->tableSize('xx')`,
try `$client->tablesSize()`

**Comment by isublimity** [comment]
see 
```
var_dump($client->tablesSize());

```

**Comment by isublimity** [comment]
bug in code , i fix

**Comment by isublimity** [comment]
Fix in 1.0.0 

https://github.com/smi2/phpClickHouse/releases/tag/1.0.0
