### ISSUE TITLE
Drop support for legacy PHP versions

### ISSUE THREAD

**Issue by simPod** [smi2/phpClickHouse#69]
_I have mentioned it few times ago, creating this issue just to be notified, when it is dropped so I don't have to come back regularly and read commits :)_

Current PHP version is 7.2, 7.3 will be released soon.

5.6 is ~4 years old, currently with security support only, EOL in 5 months.
7.0 EOL in 6 months

Therefore, old php versions support should be dropped and 7.1 set as minimum requirement.

https://secure.php.net/supported-versions.php

**Comment by isublimity** [comment]
I do not see any problems in that the library supports the old version, and I think this does not affect its quality and security.
If you are using the latest version of PHP in the project - support for the old version does not bother you. 
And i repeat - I need support for this version

**Comment by isublimity** [comment]
31 Dec 2018 - i delete support 5.6)

**Comment by simPod** [comment]
Security not yet, but quality it does. Eg. 
- you cannot run higher levels of PHPStan and 
- cannot use more strict type definitions.

The result is that the types are ofter incorrectly documented and I'd bet there are many bugs that we haven't found yet because of those two.

31. 12. it is then, note taken.

**Comment by simPod** [comment]
_Btw, wasn't meant this to be hostile, I know you mentioned it earlier there's a project of yours running on lower PHP version. That's why I created issue only and not PR._

**Comment by isublimity** [comment]
i'm ask community drop 5.6

**Comment by isublimity** [comment]
I drop 5.6

**Comment by simPod** [comment]
👏 

I suggest to make it ^7.1 straight as 7.0's EOL is in 6 months anyway. 7.1 brings cool features like nullables or void types and compared to 7.0 is not very different
