### ISSUE TITLE
Move changelog to Releases

### ISSUE THREAD

**Issue by simPod** [smi2/phpClickHouse#73]
I propose to remove [Changelog section](https://github.com/smi2/phpClickHouse/blob/master/README.md#changelog) from README and document changes in https://github.com/smi2/phpClickHouse/releases. What do you think? 

Personally, I think readme is too long and would be fine to clean it up a little.

**Comment by isublimity** [comment]
Yes you are right) 
I add CHANGELOG.md like ) 
```
https://github.com/yandex/ClickHouse/blob/master/CHANGELOG.md
```

It's easier for me to see changes in one file
