### ISSUE TITLE
cURL + fopen/fclose 

### ISSUE THREAD

**Issue by AntonSaykovsky** [smi2/phpClickHouse#74]
Добрый день.

Есть необходимость использовать прямую запись в файл (именно через простой select):

```
$WriteToFile=new ClickHouseDB\WriteToFile('/tmp/_1_select.csv');
$db->select('select * from summing_url_views',[],null,$WriteToFile);
```

Однако, мне бы хотелось иметь возможность писать в уже существующий файл (с данными), а также дополнять его сразу после записи.

Огромная просьба вывести в параметры WriteToFile мод fopen в getRequestRead() в Http.php.

Заранее большое спасибо!

**Comment by isublimity** [comment]
Попробуйте stream 

```php

$stream = fopen('php://memory','r+');
$streamRead=new ClickHouseDB\Transport\StreamRead($stream);
$r=$client->streamRead($streamRead,'SELECT sin(number) as sin,cos(number) as cos FROM {table_name} LIMIT 4 FORMAT JSONEachRow', ['table_name'=>'system.numbers']);
rewind($stream);
while (($buffer = fgets($stream, 4096)) !== false) {
    echo ">>> ".$buffer;
}
fclose($stream);

```

**Comment by isublimity** [comment]
https://github.com/smi2/phpClickHouse/blob/master/example/exam23_streams.php

**Comment by AntonSaykovsky** [comment]
При стриме валится память к сожалению.

**Comment by isublimity** [comment]
Если fopen направлен на файл?
StreamRead аналог 
```
fopen('./ttt.csv','r+)
```
