### ISSUE TITLE
Why is dropOldPartitions() deprecated

### ISSUE THREAD

**Issue by simPod** [smi2/phpClickHouse#82]
Hello, why is `dropOldPartitions()` deprecated? Thanks!

**Comment by isublimity** [comment]
Clickhouse support DDL,
I recommend not using this code ( in driver ) - it was not tested on the latest versions CH on Cluster mode.
You can copy code to your php - its simple -> select -> foreach -> alter table  -- and test work

**Comment by isublimity** [comment]
And it seems to me, that this function is beyond the ch_driver ;)

**Comment by simPod** [comment]
Yup, I copied it to my code. I was just wondering whether there wasn't something I could fix for example. I have no experience with cluster yet (coming soon) so can't help with testing :) . I just know it doesn't work when not partitioning by `Date` type column as max/min date is not set in `system.parts`.

Thanks for reply!
