### ISSUE TITLE
Strings in array are not escaped correctly

### ISSUE THREAD

**Issue by 2ur1st** [smi2/phpClickHouse#85]
To get that error you should to execute function 
`FormatLine::CSV();`

Simple example:
```
$str = '"name", "age", "['\"That does not\"', 'That work']"';
FormatLine::CSV($str);
```
To fix this case I replaced all double quotes to single quotes for array

**Comment by simPod** [comment]
@2ur1st can you send a PR with fix pls? You seem to have a real life use case so it's the best opportunity to fix the issue and cover it with test so it doesn't get broken again :)

**Comment by 2ur1st** [comment]
@simPod #86
