### ISSUE TITLE
phpclickhouse consume too much memory

### ISSUE THREAD

**Issue by kstan79** [smi2/phpClickHouse#89]
Hi,
I notice phpclickhouse consume significant of resources, example:
I have a table have roughly 750,000 rows of records.

Init workerman, before run sql select() memory usage: 2.47 mb
after run SQL select($sql) (but fetch rows() ), memory usage: 719.42 mb
after rows(), memory usage: 3.47 gb
Is there any method to reduce into minimal?
Thanks,
KS Tan

**Comment by 2ur1st** [comment]
Hello, 
You can try use `Client::streamRead()` to process data line by line without allocated huge amount of memory, the example you can find there `\PHPUnit\Framework\TestCase\StreamTest`

**Comment by isublimity** [comment]
Yes, phpCH allocate twice all data in memory
First - read text in json format
Second - convert json to Array

Use stream, see test and example/exam23_streams.php
