### ISSUE TITLE
Auth error on empty username and password

### ISSUE THREAD

**Issue by ova777** [smi2/phpClickHouse#93]
With empty login and password, I get an authorization error.
Fix in CurlerRequest.php::438
`if (!empty($username)) {
    $this->options[CURLOPT_USERPWD] = sprintf("%s:%s", $username, $password);
}`

**Comment by simPod** [comment]
How do you construct a Client?

**Comment by ova777** [comment]
Oh, I am sorry. It works fine with username 'default' and empty password. I close the issue.
